//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; C:\Users\Axel Lacapmesure\Google Drive\Facultad\2018_InstrumentacionYControl\afinador\prueba.py
///  Source class: Afinador2
///  Generation timestamp: 2018-12-10T15:34:52.194150
///  Class code hash: d8b86d2c295de2e888b64d479673cf2192e638e3
///
/////////////////////////////////////////////////////////////

#ifndef inodriver_user_h
#define inodriver_user_h

#include <Arduino.h>

#define LENGTH 256
#define FREQ 38461 // Frecuencia de sampleo medida 


// Métodos propios
float compute_mean(int* input, int len);
int detect_frequency(int* input, float threshold_ratio, float* corr, int len);

// Métodos de SerialCommand
void user_setup();
void user_loop();
int get_TUN(); 
int set_TUN(int); 
float get_REF(); 
int set_REF(float); 
float get_DIFF(); 
int set_DIFF(float); 
int get_LEN(); 
int set_LEN(int); 
float get_TOL(); 
int set_TOL(float);


#endif // inodriver_user_h
